### ISSUE TITLE
[Front?][Back] Markdown quebrado no desafio da stone

### ISSUE THREAD

**Issue by francisko-rezende** [codante-io/codante-io-front#158]
# Markdown quebrado no desafio da stone

A imagem do figma da página do desafio da stone está quebrada, está assim:

![image](https://github.com/codante-io/codante-io-front/assets/39991049/dd956ad1-0e1c-476b-869d-c6297189c5b5)

![image](https://github.com/codante-io/codante-io-front/assets/39991049/acc770c2-2ba8-4fe3-ac57-3ee586a5bb17)

Pelo que vi, essa parte é renderizada usando markdown com dados que são puxados do servidor (o componente MarkdownRenederer recebe o valor `assessment.assessment_instructions_text` na prop `markdown` e o assesmente vem de uma chamada realizada no arquivo `assessments.server.ts`. Ou seja, capaz que o problema não é bem no front.

**Comment by icaroharry** [comment]
Valeu pelo feedback @francisko-rezende!

Vamos arrumar aqui.

**Comment by felipemuller20** [comment]
Ajustado 😄
