### ISSUE TITLE
[Front] Scroll lateral na tela Agenda

### ISSUE THREAD

**Issue by EduCsg** [codante-io/codante-io-front#41]
## Scroll Lateral na tela Agenda

Ao abrir a tela de Agenda e clicar na opção de "Incluir no Calendário", surge um Scroll Lateral

## Exemplo

![image](https://github.com/codante-io/codante-io-front/assets/82413446/8749be68-c06a-49c8-a696-c9c6ac0153d9)

Após clicar para incluir no calendário, o Scroll aparece
![image](https://github.com/codante-io/codante-io-front/assets/82413446/37aa969d-89b6-4c92-9868-900f15c44acf)

## Adicional

Não sei se o próximo erro será considerado como BUG, entretanto, o cursor personalizado dessa mesma tela só fica disponível em algumas áreas específicas:

Dentro da área destacada em Vermelho, o cursor aparece corretamente
![image](https://github.com/codante-io/codante-io-front/assets/82413446/05c033e6-f8a0-4272-8237-8c86d25bf6cc)

Fora da área vermelha, o cursor volta ao default
![image](https://github.com/codante-io/codante-io-front/assets/82413446/c2972e3d-c623-4ad0-bc66-1e52aa44eeb6)

### OBS: Essa div é quem está causando o scroll lateral

Tentei realizar a correção para abrir um PR, porém estou recebendo um erro ao clonar o repositório e tentar abrir o mesmo na minha rede (Provavelmente devido a conexão ao BD)

**Comment by icaroharry** [comment]
Valeu pelo feedback @EduCsg!

Essa tela foi desativada por enquanto, por isso vou fechar a issue.

Abraço!
